version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: restaurant_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - restaurant_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: restaurant_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - restaurant_network

volumes:
  mariadb_data:

networks:
  restaurant_network:
    driver: bridge
